### ISSUE TITLE
 sh: 1: title: not found

### ISSUE THREAD

**Issue by 9ofe** [KevinLage/Spotify-Account-Creator#1]
it spam 

sh: 1: title: not found
sh: 1: title: not found
sh: 1: title: not found
sh: 1: title: not found
sh: 1: title: not found
sh: 1: title: not found
sh: 1: title: not found
sh: 1: title: not found
sh: 1: title: not found
sh: 1: title: not found
sh: 1: title: not found
sh: 1: title: not found
sh: 1: title: not found
sh: 1: title: not found

**Comment by KevinLage** [comment]
wont work on Linux

you have to remove the title part

**Comment by KevinLage** [comment]
gimme a few minutes to update it

**Comment by KevinLage** [comment]
Please test the updated version

**Comment by 9ofe** [comment]
i waited 20min .. no results 
nothing after

How many accounts do you want to create?
50
How many Threads?
50

**Comment by KevinLage** [comment]
it should have created a "created.txt"

**Comment by 9ofe** [comment]
It didn't create any files. :(

**Comment by KevinLage** [comment]
which OS are u using?

**Comment by 9ofe** [comment]
Linux
Ubuntu 18.04

**Comment by KevinLage** [comment]
read #2

**Comment by 9ofe** [comment]
Thanks <3
