### ISSUE TITLE
Error:0

### ISSUE THREAD

**Issue by baiaelmillantater** [KevinLage/Spotify-Account-Creator#2]
Error:0 with either the python version and exe version
theres no created.txt file
![asdasd](https://user-images.githubusercontent.com/67751168/86378306-cf23e900-bc89-11ea-9448-89a2ad8cf843.PNG)

**Comment by KevinLage** [comment]
does the created counter change?

**Comment by baiaelmillantater** [comment]
No, i had it running in background for 20 minutes now

**Comment by KevinLage** [comment]
[baiaelmillantater.py.zip](https://github.com/KevinLage/Spotify-Account-Creator/files/4865409/baiaelmillantater.py.zip)

pls run this python file and tell me which errors you get

**Comment by baiaelmillantater** [comment]
![asdasdasd](https://user-images.githubusercontent.com/67751168/86383161-52dfd480-bc8e-11ea-9a29-94e54194bfa3.PNG)

**Comment by KevinLage** [comment]
oh yeah you have to install pysocks

https://stackoverflow.com/questions/12601316/how-to-make-python-requests-work-via-socks-proxy

**Comment by baiaelmillantater** [comment]
Thanks a lot, now it works

**Comment by KevinLage** [comment]
no Problem
